controller_manager:
  ros__parameters:
    update_rate: 100  # Control loop update rate in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_controller:
      # type: joint_trajectory_controller/JointTrajectoryController
      type: position_controllers/JointGroupPositionController 

hardware_interface:
  ros__parameters:
    type: mock_components/GenericSystemMultiInterface  

joint_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
