controller_manager:
  ros__parameters:
    update_rate: 1000  # Control loop update rate in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster     

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity