controller_manager:
  ros__parameters:
    update_rate: 100  # Control loop update rate in Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_1_controller:
      type: position_controllers/JointGroupPositionController  # Specify controller type

hardware_interface:
  ros__parameters:
    type: mock_components/GenericSystem  

joint_1_controller:
  ros__parameters:
    joints:
      - joint_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    pid:
      p: 100.0
      d: 1.0
      i: 0.1
      i_clamp: 1.0
    allow_partial_joints_goal: true
    open_loop_control: false
